### ISSUE TITLE
Not all features working and setting page is empty

### ISSUE THREAD

**Issue by ghostscript3r** [ghostscript3r/poe-trade-enhancer#1]
Issue for at least 3 users and signaled from ThorTheGray

First thing to check is javascript errors.

ThorTheGray hit F12 then click console and send me a screenshot of what you have there (ngtrungkhanh and SingleInfinity too if you can)

If you have problems doing or sending the screenshot hot CTRL-A and CTRL-C to copy all text, but it will be harder to read.

![2019-07-19_10h10_27](https://user-images.githubusercontent.com/52499304/61520127-ca7d0b00-aa0d-11e9-86fb-6341142177eb.png)

**Comment by ThorTheGray** [comment]
It seems i only have one error.
![image](https://user-images.githubusercontent.com/51345741/61568850-fb336380-aa52-11e9-8edb-ed5958a1c310.png)

**Comment by ngtrungkhanh** [comment]
I have same problem.

![](https://i.imgur.com/9Zinis4.png)

**Comment by ghostscript3r** [comment]
Doesn't make much sense yet.
Can you try edit the script and at line 28 change DEBUG from false to true. Save and refresh the page. You should see on console a lot of text. Send me that screen shot, it should give me some indication of where it's not working

**Comment by ngtrungkhanh** [comment]
![image](https://user-images.githubusercontent.com/39927526/61576322-ed3d1b80-ab02-11e9-8203-5a0ebd99dd7b.png)

Not sure if i did it right or not.

**Comment by ghostscript3r** [comment]
Yes you did it exactly right. But doesn't make sense yet. It seems to stop
for a page error, but that should mean that at least some functions of the
original page shouldn't work too.

I'll try to reproduce it but it's not easy.

I'll get back at you as soon as I have something to let you try for me.

Il sab 20 lug 2019, 10:28 ngtrungkhanh <notifications@github.com> ha
scritto:

**Comment by ghostscript3r** [comment]
Ok, please disable the script and install this one:
https://www.dropbox.com/s/i7ttja8zqi9evz8/poe-trade-enhancer.user.js?raw=1
it's the one I use to develop new features.
Run once with this and send me the screenshot (debug is already true)
Then set DELAY to 5000 (row under DEBUG) and run it again.
Give it few seconds because the script will start after 5 seconds and then send me the screenshot.

thx for taking the time to help debug it

**Comment by ngtrungkhanh** [comment]
![image](https://user-images.githubusercontent.com/39927526/61578134-1ddd7f00-ab1c-11e9-9a42-047ff993292e.png)
![image](https://user-images.githubusercontent.com/39927526/61578143-41082e80-ab1c-11e9-90ce-0d7d70b48ac1.png)

**Comment by ghostscript3r** [comment]
Updae the DEV script (you should see 1.1.30 as version) and send me the screenshot. We should be near finding the problem

**Comment by ngtrungkhanh** [comment]
![image](https://user-images.githubusercontent.com/39927526/61578557-41f08e80-ab23-11e9-9677-ac9ae2525542.png)
This was tested in my other computer, same chrome account, different window version, different network.

**Comment by ngtrungkhanh** [comment]
![image](https://user-images.githubusercontent.com/39927526/61578583-a3b0f880-ab23-11e9-8a38-c8a6eb1048ab.png)
Here with ublock disable

**Comment by ngtrungkhanh** [comment]
BTW, i had teamviewer installed, in case you need.

**Comment by ghostscript3r** [comment]
At least I know what's wrong now, the iframe on load event doesn't fire. I'll search for a known solution because the code I used is the only guaranteed to work also in firefox.
I'll have to get back to it in about ten hours though. If you are available then teamviewer might be very useful, because I can't reproduce the problem on any of my chromes.

**Comment by ghostscript3r** [comment]
Try to update again (1.1.31). This should work, but not in firefox

**Comment by ThorTheGray** [comment]
Just woke up and tried again. I still get nothing in the settings panel but it seems to be working for searches. 

Edit: The buttons to save searches do nothing as well. 

![error 1](https://user-images.githubusercontent.com/51345741/61579383-46d92200-aad2-11e9-8325-c443e0a1116e.JPG)
![error 2](https://user-images.githubusercontent.com/51345741/61579384-4a6ca900-aad2-11e9-95d5-18e4a8890122.JPG)
![error 3](https://user-images.githubusercontent.com/51345741/61579386-4ccf0300-aad2-11e9-9c14-ae59989597f3.JPG)
![error 4](https://user-images.githubusercontent.com/51345741/61579387-4e98c680-aad2-11e9-9968-9c93f0f4c08f.JPG)

**Comment by ngtrungkhanh** [comment]
I got the same result as ThorTheGray

**Comment by ghostscript3r** [comment]
Can you try again updating the dev script? 
If I'm right now it should work, but I'll need to try some other solution because this way I'm sure it doesn't work in firefox

**Comment by ThorTheGray** [comment]
Seems I now can see settings however saving a search produces errors.

![111](https://user-images.githubusercontent.com/51345741/61584776-81b37800-ab1b-11e9-8780-8ee8e418e875.JPG)
![112](https://user-images.githubusercontent.com/51345741/61584777-84ae6880-ab1b-11e9-95ee-812eac1fbb44.JPG)

**Comment by ghostscript3r** [comment]
I need teamviewer for this... can't reproduce this even using your search exactly
Do you have it? If so PM me your ID. If not try clicking on ":1965" (the first link inside the error block) and send me a screen of where it opens

**Comment by ThorTheGray** [comment]
Not familiar with teamviewer but I included where 1965 goes. 

![image](https://user-images.githubusercontent.com/51345741/61585342-1f607480-ab27-11e9-8c56-3336c03ad63f.png)

**Comment by ngtrungkhanh** [comment]
> I need teamviewer for this... can't reproduce this even using your search exactly
> Do you have it? If so PM me your ID. If not try clicking on ":1965" (the first link inside the error block) and send me a screen of where it opens

Tell me your email, (tempmail is ok,) so i can send my id/pass
Githut dont have private message feature

**Comment by ghostscript3r** [comment]
Sorry, thought my mail was already visible. 
ghostscript3r@gmail.com
Before that try out new version 1.1.38, it might be a long shot, but might work.
I have another one to try before teamviewer if this doesn't work

**Comment by ThorTheGray** [comment]
I can verify that 1.1.41 is seemingly fully operational.

**Comment by ngtrungkhanh** [comment]
Same here

**Comment by ghostscript3r** [comment]
encouraging at least, but this version have problems for me that I didn't have before, using chrome too.

can you check few things for me:
do you see other userscript errors?
autocomplete in save window works?
renaming a search in load window shows a modal and the renaming works?
in both save and load close button works?
if you edit the script and remove line 8 (// @connect      poe.ninja) does everything still work?

**Comment by ThorTheGray** [comment]
If you mean by does the search autocomplete which saved search you are looking for then yes.
Renaming a search worked for me in the Load screen. 
Both close buttons do what they are intended to do. 
I haven't tried modding the script as I am unsure on how to do so.

**Comment by ghostscript3r** [comment]
Can you upgrade and confirm that 1.1.52 still works for you?
This works for my chrome and for firefox, and should work for you too. I'll publish this version as soon as one of you confirm me it's working

**Comment by ghostscript3r** [comment]
Can someone test it? I can't reproduce it so I can't test it myself

**Comment by ThorTheGray** [comment]
I'll verify when I get home from work.

**Comment by ngtrungkhanh** [comment]
Sorry for late reply. It worked for me. But i had found a bug.
Here is the first search.
![image](https://user-images.githubusercontent.com/39927526/61675982-7f703a00-ad24-11e9-9b23-59fc3fde1aa1.png)
After i clicked "7 more from same user" - i still see IGN: Sofa_king..... (6 more hydraTheking is below)
![image](https://user-images.githubusercontent.com/39927526/61676049-ca8a4d00-ad24-11e9-8031-9fb1e7b929a2.png)
After i clicked "7 more from same user" one more time, hydraTheking disappear (he is put lower - at 6th)
![image](https://user-images.githubusercontent.com/39927526/61676188-38cf0f80-ad25-11e9-9d9c-fc33d3326265.png)

**Comment by ngtrungkhanh** [comment]
http://poe.trade/search/ihiononakamudu
link of the search

**Comment by ThorTheGray** [comment]
I could not test it last night since I had a power outage. Will test tonight.

**Comment by ghostscript3r** [comment]
ngtrungkhanh from what I'm seeing it's working as designed. Still the design might be improved :)
what I mean is when results are grouped they are sorted by average price of all element in group. This is because I usually use only for maps and similar, things I'd like to buy in bunch but mostly at same price. It doesn't work very well with complex item searches where every item can have completely different price, but also completely different mods.
When you ungroup it sorts for real poe.ninja value, so if you don't auto sort for that it should sort for original poe.trade order. That could be improved for sure.

**Comment by ghostscript3r** [comment]
I'd say it's working, I'm pushing a new release with the fix. You should stop using the dev one then. I'm going to some developments in the next and that can brake anytime and also stay broken for days.

**Comment by ThorTheGray** [comment]
I updated to the non-dev version and it seems to be ok.

**Comment by ghostscript3r** [comment]
Thank you very much to everybody
