### ISSUE TITLE
League multi live search bug

### ISSUE THREAD

**Issue by GLADpwnz** [ghostscript3r/poe-trade-enhancer#3]
thx for great work, but i noticed that the script does not work correctly in the new league

![request data screenshot](https://i.imgur.com/k6yL7nU.jpg)
```javascript
$.ajax({
  url: window.location.protocol + "//poe.trade/search",
  type: 'POST',
  data: JSON.stringify(search),
  contentType: "application/x-www-form-urlencoded",
  xhr: function() {
       return xhr;
  }
}
```
can be fixed with this
```javascript
- data: JSON.stringify(search),
+ data: search,
```
please check and fix it, ty!

**Comment by ghostscript3r** [comment]
Don't know why I didn't receive a notification of this... But it has already been fixed in 1.2.20 exactly like you suggested. Thank you very much for the help! Even if I didn't realize it in time I surely appreciate the effort. Having someone helping with debug is invaluable for a one man team
