### ISSUE TITLE
Cannot click "whisper" on any multi-search on poe.trade

### ISSUE THREAD

**Issue by gvieiraaa** [ghostscript3r/poe-trade-enhancer#4]
I can't click "whisper" on any item when it's on a multi-search (only on poe.trade): https://i.imgur.com/VPFT7sf.png

It works fine on pathofexile.com/trade

Console doesn't seem to help much: https://i.imgur.com/04zWSDP.png

Tested in Chrome (76.0.3809.132) and Brave (Chromium: 76.0.3809.132) (basically the same thing, I know)

**Comment by ghostscript3r** [comment]
You will have to activate debug to see some more information. Go to Dashboard and edit the script, then change line 29 to DEBUG = true. CTRL+S to save, then try again.
To be clear you see the whisper link, it just doesn't copy to clipboard right? If try to send me a screenshot of the console before clicking and after clicking. Let's pin this down.

**Comment by top1apelsin** [comment]
https://i.imgur.com/V7CTjFL.png - with multisearch
https://i.imgur.com/08KYEKq.png - just normal search

**Comment by ghostscript3r** [comment]
Been able to replicate the problem. Those where not the screenshot I asked but apparently where the ones I needed :)
The problem seem to be related to the "starting point" of multi live search. If you start it from a clean search form (http://poe.trade/) whispers do not work. If you start from a search result (ex: http://poe.trade/search/azuwaunizukasi) whispers work. At least that what it does for me. I'll try to solve this as soon as I can, but you have a workaround for the time being.

If you still have the problem of multi live not starting at all with 4+ searches for that I will need the debug messages from console. I need something like this: https://imgur.com/HfBPrKW

To activate debug you need to do this: https://imgur.com/21t5g6Z

Make sure console is showing debug level messages: https://imgur.com/ws8DTuw

**Comment by ghostscript3r** [comment]
Upgrade to 1.2.37 
now whispers work even if you start from an empty search form

**Comment by gvieiraaa** [comment]
Thanks! Sorry for not helping much, I had no idea how to use debug
