### ISSUE TITLE
Cannot edit searches

### ISSUE THREAD

**Issue by leet0rz** [ghostscript3r/poe-trade-enhancer#6]
After clicking on this it opens a fresh tab so saved searches cannot be opened on poe.trade
https://i.imgur.com/BXJ38iI.png

**Comment by knivesss** [comment]
just change the "http" to "https" on the line 1327

**Comment by leet0rz** [comment]
They are all https.

**Comment by ghostscript3r** [comment]
Hi, I still needed to change to https. poe.trade works only over https now so it's a simpler situation. You shouldn't experience this problem anymore. Feel free to reopen if you experience this even with latest release. v. 1.3.379
