### ISSUE TITLE
Chrome Liver search Error

### ISSUE THREAD

**Issue by Elezen514** [ghostscript3r/poe-trade-enhancer#9]
When i'm using the live search function it keep saying 

Live Search Error 
An Error Occurred While Connecting

Disconnected from server
Retrying connection in ## seconds..

It was working fine the first few week and now this hope someone can help
Thank you

**Comment by Elezen514** [comment]
![image](https://user-images.githubusercontent.com/59316216/73046783-5f3f4600-3e41-11ea-8299-c1e4756dfeee.png)

**Comment by ghostscript3r** [comment]
I've been able to reproduce this and it should be solved with latest release 1.3.379. Feel free to reopen the issue if you still experience it.
